name: chitchat

description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # used for responsive design
  flutter_screenutil: ^5.9.3
  # used for state management
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  # used to generate the splash screen
  flutter_native_splash: ^2.4.1
  # used for using svg images
  flutter_svg: ^2.0.10+1
  # used in firebase authentication using google
  google_sign_in: ^6.2.1
  # used in firebase authentication
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  flutter_facebook_auth: ^7.0.1
  flutter_slidable: ^3.1.1
  cloud_firestore: ^5.4.5
  shared_preferences: ^2.3.3
  cached_network_image: ^3.4.1
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/svgs/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900  
  
flutter_assets:
  assets_path: assets/
  output_path: lib/src/core/constants/
  filename: assets.dart