class FirebaseStrings {
  static const String users = 'users';
  static const String phone = 'phone';
  static const String email = 'email';
  static const String name = 'name';
  static const String userID = 'uId';
  static const String bio = 'bio';
  static const String chats = 'chats';
  static const String photo = 'photo';
  static const String lastSeen = 'lastSeen';
  static const String lastActivity = 'lastActivity';
  static const String messages = 'messages';
  static const String message = 'message';
  static const String dateTime = 'dateTime';
  static const String receiver = 'receiver';
  static const String isSeen = 'isSeen';
  static const String text = 'text';
  static const String exists = 'exists';
  static const String signaling = 'signaling';
  static const String callsHistory = 'callsHistory';
  static const String callerId = 'callerId';
  static const String callId = 'callId';
  static const String receiverId = 'receiverId';
  static const String offer = 'offer';
  static const String answer = 'answer';
  static const String iceCandidates = 'iceCandidates';
  static const String userNotAnswering = 'user not answering';
  static const String callStatus = 'callStatus';
}
