// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD12nNA0fULcwu5qNT1dX_uTljbpXcRkA8',
    appId: '1:931632832155:web:99c4d7e5bf17baf371f03e',
    messagingSenderId: '931632832155',
    projectId: 'chitchat-17a50',
    authDomain: 'chitchat-17a50.firebaseapp.com',
    storageBucket: 'chitchat-17a50.appspot.com',
    measurementId: 'G-ECPL52TYBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClCMjdqVATOhOrSV00HAMlz6mNrm-32Cs',
    appId: '1:931632832155:android:9bc14043da9abaaa71f03e',
    messagingSenderId: '931632832155',
    projectId: 'chitchat-17a50',
    storageBucket: 'chitchat-17a50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG6-YTYMSOW3kUYmKiaHpyst9A-njdJ9U',
    appId: '1:931632832155:ios:05a9c4fb24907b0871f03e',
    messagingSenderId: '931632832155',
    projectId: 'chitchat-17a50',
    storageBucket: 'chitchat-17a50.appspot.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG6-YTYMSOW3kUYmKiaHpyst9A-njdJ9U',
    appId: '1:931632832155:ios:05a9c4fb24907b0871f03e',
    messagingSenderId: '931632832155',
    projectId: 'chitchat-17a50',
    storageBucket: 'chitchat-17a50.appspot.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD12nNA0fULcwu5qNT1dX_uTljbpXcRkA8',
    appId: '1:931632832155:web:d5effcc644601a1a71f03e',
    messagingSenderId: '931632832155',
    projectId: 'chitchat-17a50',
    authDomain: 'chitchat-17a50.firebaseapp.com',
    storageBucket: 'chitchat-17a50.appspot.com',
    measurementId: 'G-4TWE6P9F09',
  );

}