name: Build & Distribute to Firebase for testing

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Skip APK build (test only)'
        required: false
        type: boolean
        default: false

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      # Create dummy APK in test mode
      - name: Create dummy APK
        if: ${{ inputs.test_mode }}
        run: |
          mkdir -p build/app/outputs/flutter-apk/
          echo "Dummy APK for testing" > build/app/outputs/flutter-apk/app-release.apk
          echo "✅ Created dummy APK"

      # Build real APK in production mode
      - name: Build APK
        if: ${{ !inputs.test_mode }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          args: build apk --release

      # Distribute to Firebase using token auth
      - name: Distribute to Firebase
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --testers "mohamedhalim2991@gmail.com" \
            --release-notes "Run ${{ github.run_id }} demo"