name: Build & Distribute to Firebase

on:
  push:
    branches: 
      - main

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: '3.32.0'

      # - name: Install dependencies
      #   run: flutter pub get

      # - name: Build APK
      #   run: flutter build apk --release

       # Create dummy APK for testing
      - name: Create dummy APK
        if: ${{ github.event.inputs.test_mode }}
        run: |
          mkdir -p build/app/outputs/flutter-apk/
          echo "Dummy APK for testing" > build/app/outputs/flutter-apk/app-release.apk
          echo "✅ Created dummy APK (test mode)"

      # - name: Set up Node.js 20
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Create service account file
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json


      # - name: Authenticate with Service Account
      #   run: |
      #     gcloud auth activate-service-account --key-file=firebase-service-account.json
      #     gcloud config set project chitchat-17a50
      #     gcloud auth list

      - name: Distribute to Firebase 
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
        run: |
          firebase projects:list  # Verify auth
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --testers "mohamedhalim2991@gmail.com" \
            --release-notes "uploaded using GitHub actions"