name: Build & Distribute to Firebase

on:
  push:
    branches: 
      - main

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: '3.32.0'

      # - name: Install dependencies
      #   run: flutter pub get

      # - name: Build APK
      #   run: flutter build apk --release

       # Create dummy APK for testing
      - name: Create dummy APK
        run: |
          mkdir -p build/app/outputs/flutter-apk/
          echo "Dummy APK for testing" > build/app/outputs/flutter-apk/app-release.apk

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      # you must create FIREBASE_SERVICE_ACCOUNT which contain json file from firebase
      - name: Create service account file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json

      - name: Distribute to Firebase 
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --testers "mohamedhalim2991@gmail.com" \
            --release-notes "uploaded using GitHub actions"